In [48]:
import pandas as pd
df = pd.read_csv("survey lung cancer.csv")

In [49]:
df.head(100)

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER
0,M,69,1,2,2,1,1,2,1,2,2,2,2,2,2,YES
1,M,74,2,1,1,1,2,2,2,1,1,1,2,2,2,YES
2,F,59,1,1,1,2,1,2,1,2,1,2,2,1,2,NO
3,M,63,2,2,2,1,1,1,1,1,2,1,1,2,2,NO
4,F,63,1,2,1,1,1,1,1,2,1,2,2,1,1,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,M,60,1,2,2,2,1,2,1,1,1,1,1,2,2,YES
96,F,61,2,2,2,1,1,1,2,1,2,2,2,1,2,YES
97,M,59,2,1,1,2,1,1,1,1,2,2,2,1,1,YES
98,M,64,1,2,2,2,1,2,2,1,1,2,1,2,1,YES
99,M,56,2,1,1,1,1,2,2,2,2,2,2,1,2,YES

In [50]:
df.info()
df["GENDER"].replace(["M","F"], [0,1], inplace=True)
df["LUNG_CANCER"].replace(["YES","NO"], [1,0], inplace=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 309 entries, 0 to 308
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   GENDER                 309 non-null    object
 1   AGE                    309 non-null    int64
 2   SMOKING                309 non-null    int64
 3   YELLOW_FINGERS         309 non-null    int64
 4   ANXIETY                309 non-null    int64
 5   PEER_PRESSURE          309 non-null    int64
 6   CHRONIC DISEASE        309 non-null    int64
 7   FATIGUE                309 non-null    int64
 8   ALLERGY                309 non-null    int64
 9   WHEEZING               309 non-null    int64
 10  ALCOHOL CONSUMING      309 non-null    int64
 11  COUGHING               309 non-null    int64
 12  SHORTNESS OF BREATH    309 non-null    int64
 13  SWALLOWING DIFFICULTY  309 non-null    int64
 14  CHEST PAIN             309 non-null    int64
 15  LUNG_CANCER            309 non-null    object
dtypes: int64(14), object(2)
memory usage: 38.8+ KB

In [51]:
df = pd.get_dummies(df)
df

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER
0,0,69,1,2,2,1,1,2,1,2,2,2,2,2,2,1
1,0,74,2,1,1,1,2,2,2,1,1,1,2,2,2,1
2,1,59,1,1,1,2,1,2,1,2,1,2,2,1,2,0
3,0,63,2,2,2,1,1,1,1,1,2,1,1,2,2,0
4,1,63,1,2,1,1,1,1,1,2,1,2,2,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304,1,56,1,1,1,2,2,2,1,1,2,2,2,2,1,1
305,0,70,2,1,1,1,1,2,2,2,2,2,2,1,2,1
306,0,58,2,1,1,1,1,1,2,2,2,2,1,1,2,1
307,0,67,2,1,2,1,1,2,2,1,2,2,2,1,2,1
308,0,62,1,1,1,2,1,2,2,2,2,1,1,2,1,1

In [52]:
prediction = ['GENDER','AGE','SMOKING','YELLOW_FINGERS','CHRONIC DISEASE','WHEEZING','COUGHING','SHORTNESS OF BREATH','SWALLOWING DIFFICULTY','CHEST PAIN']
x = df[prediction]

y = df['LUNG_CANCER']

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(x)
scaled_df = scaler.transform(x)
scaled_df = pd.DataFrame(scaled_df, columns= x.columns)
scaled_df.head()

,GENDER,AGE,SMOKING,YELLOW_FINGERS,CHRONIC DISEASE,WHEEZING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN
0,-0.952579,0.771850,-1.135292,0.869300,-1.009756,0.892475,0.852207,0.748736,1.063501,0.892475
1,-0.952579,1.381829,0.880830,-1.150351,0.990338,-1.120480,-1.173424,0.748736,1.063501,0.892475
2,1.049781,-0.448107,-1.135292,-1.150351,-1.009756,0.892475,0.852207,0.748736,-0.940291,0.892475
3,-0.952579,0.039876,0.880830,0.869300,-1.009756,-1.120480,-1.173424,-1.335584,1.063501,0.892475
4,1.049781,0.039876,-1.135292,0.869300,-1.009756,0.892475,0.852207,0.748736,-0.940291,-1.120480

In [53]:
from sklearn.model_selection import train_test_split
x_train,x_test, y_train,y_test = train_test_split(scaled_df, y , test_size=0.9, random_state=42)
print(len(y_test))

279

In [54]:
from sklearn import linear_model

model = linear_model.LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [55]:
model.score(x_test,y_test)

0.8637992831541219